### ISSUE TITLE
Frontend layout/design

### ISSUE THREAD

**Issue by fadeenk** [Lamassau/PiTrol#27]
How is the frontend control panel is going to look?
How are we going to approach different sized plugins?
Is this going to be card based/ accordion based plugins?
How do we order the plugins on the UI?

Would like to start collecting some ideas on how the front end will look like before we have people start building their plugins. 

Any suggestions will be appreciated.

**Comment by areeb111** [comment]
I am working on the frontend,
I hope i can show you something today.



On Feb 13, 2017 12:04 AM, "Fadee Kannah" <notifications@github.com> wrote:

How is the frontend control panel is going to look?
How are we going to approach different sized plugins?
Is this going to be card based/ accordion based plugins?
How do we order the plugins on the UI?

Would like to start collecting some ideas on how the front end will look
like before we have people start building their plugins.

Any suggestions will be appreciated.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fadeenk/PiTrol/issues/27>, or mute the thread

**Comment by AlKass** [comment]
I have a proposal in mind. Let me finish unifying the plugin-and-react-component part and will present the frontend design to the team

**Comment by areeb111** [comment]
Please check the "/ui-test" from your side and let me know if it's OK, So i can proceed.

**Comment by AlhasanIQ** [comment]
did check it,
it is neat an minimal,

we need to port it to react though;

**Comment by AlhasanIQ** [comment]
and btw, please commit to your fork and create a Pull Request ,
dont commit to the repo's master.
only fork

**Comment by AlhasanIQ** [comment]
please approve this ui so that i can set it up in react

@AlKass @fadeenk @Ahmed-90

**Comment by fadeenk** [comment]
I would love to see/approve it, but I am away from my PC so I don't know wts going on :(

**Comment by Ahmed-90** [comment]
@AlhasanIQ in the middle of a project can you screen it? 😜

**Comment by AlhasanIQ** [comment]
![screenshot](http://i.imgur.com/f6acxzo.png)

**Comment by fadeenk** [comment]
I love it!!!!! 
This design is great
Based on the design plugins can have a full page interface and a widget interface (for dashboard) which covers everything I think

**Comment by Ahmed-90** [comment]
exactly what we need keep it minimal

**Comment by AlKass** [comment]
I like the layout a lot
I can port the template to react if no one is able to get this part done within a day or two from today

**Comment by fadeenk** [comment]
I love the ui however I am going to revert it and put it on a branch so it doesn't break the build and cause other issues. Nothing should be pushed to master that breaks the build.

Those who agree thumbs up this post and if it gets 3+ I will clean it up

**Comment by fadeenk** [comment]
@AlhasanIQ @areeb111  summoning you to take a look at my previous comment :D

**Comment by AlKass** [comment]
is there a reason why this issue is still open?

**Comment by fadeenk** [comment]
nothing on my end
